name: biblia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Mapeo completo de todos los assets requeridos por la aplicación
  assets:
    - assets/biblia.json
    - assets/bibliaNTV.json
    - assets/bibliaTLA.json
    - assets/icon/logo.png
    - assets/splash/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter_native_splash:
  color: "#0D47A1"
  image: assets/splash/logo.png

  android_12:
    image: assets/splash/logo.png
    color: "#0D47A1"